# Generated by Django 6.0.1 on 2026-01-24 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('code', 'Code'), ('offer', 'Offer'), ('membership_reward', 'Membership Reward'), ('point_reedem', 'Point Reddmem')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('img_url', models.URLField(blank=True, max_length=500, null=True)),
                ('min_item_quantity', models.IntegerField(default=0)),
                ('min_item_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_precentage', models.IntegerField(default=0)),
                ('max_nominal_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_last_updated', models.DateTimeField(auto_now=True)),
                ('datetime_started', models.DateTimeField(blank=True, null=True)),
                ('datetime_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVoucherOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.voucherorder')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherOrderCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('datetime_started', models.DateTimeField(blank=True, null=True)),
                ('datetime_ended', models.DateTimeField(blank=True, null=True)),
                ('voucher_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voucher.voucherorder')),
            ],
        ),
    ]
