# Generated by Django 6.0.1 on 2026-01-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherorder',
            name='discount_precentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='voucherorder',
            name='min_item_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
