# Generated by Django 6.0.1 on 2026-01-24 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')], unique=True)),
                ('name', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_point_earned', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_attached', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPointMembershipReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_claimed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherOrderMembershipReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_started', models.DateTimeField(blank=True, null=True)),
                ('datetime_ended', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointMembershipReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_earned', models.IntegerField()),
                ('datetime_started', models.DateTimeField(blank=True, null=True)),
                ('datetime_ended', models.DateTimeField(blank=True, null=True)),
                ('for_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membership')),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referal_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('point', models.IntegerField(default=0)),
                ('datetime_attached', models.DateTimeField(auto_now_add=True)),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
                ('level_up_point', models.IntegerField(default=0)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membership')),
            ],
        ),
    ]
