# Generated by Django 6.0.1 on 2026-01-24 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        ('voucher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermembershiphistory',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membership'),
        ),
        migrations.AddField(
            model_name='usermembershiphistory',
            name='user_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.usermembership'),
        ),
        migrations.AddField(
            model_name='userpointmembershipreward',
            name='point_membership_reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.pointmembershipreward'),
        ),
        migrations.AddField(
            model_name='userpointmembershipreward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherordermembershipreward',
            name='for_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
        ),
        migrations.AddField(
            model_name='voucherordermembershipreward',
            name='voucher_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voucher.voucherorder'),
        ),
    ]
