# Generated by Django 6.0.1 on 2026-01-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermembership',
            old_name='datetime_end',
            new_name='datetime_ended',
        ),
        migrations.AddField(
            model_name='usermembershiphistory',
            name='datetime_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')], unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='min_point_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointmembershipreward',
            name='point_earned',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='level_up_point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
