# Generated by Django 6.0.1 on 2026-02-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_rename_datetime_end_usermembership_datetime_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='level_up_point',
            field=models.IntegerField(default=0),
        ),
    ]
