# Generated by Django 6.0.1 on 2026-02-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_usermembership_level_up_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=20, unique=True),
        ),
    ]
