# Generated by Django 6.0.1 on 2026-01-24 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcategory'),
        ),
        migrations.AddField(
            model_name='productincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cart'),
        ),
        migrations.AddField(
            model_name='productincart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='productinstore',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='productinstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='productinstorecart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='productinstoreinflashsale',
            name='flashsale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.flashsale'),
        ),
        migrations.AddField(
            model_name='productinstoreinflashsale',
            name='product_in_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productinstore'),
        ),
        migrations.AddField(
            model_name='productinstoreinproductinstorediscount',
            name='product_in_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productinstore'),
        ),
        migrations.AddField(
            model_name='productinstoreinproductinstorediscount',
            name='product_in_store_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productinstorediscount'),
        ),
        migrations.AddField(
            model_name='productinstorepoint',
            name='product_in_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productinstore'),
        ),
        migrations.AddField(
            model_name='storecart',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='productinstorecart',
            name='store_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.storecart'),
        ),
        migrations.AddField(
            model_name='userproductfavorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='userproductfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
