# Generated by Django 6.0.1 on 2026-01-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstore',
            name='sold_count',
            field=models.IntegerField(default=0),
        ),
    ]
