# Generated by Django 6.0.1 on 2026-01-26 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productinstore_sold_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashsale',
            old_name='datetime_finished',
            new_name='datetime_ended',
        ),
        migrations.RenameField(
            model_name='productinstoreinproductinstorediscount',
            old_name='datetime_finished',
            new_name='datetime_ended',
        ),
        migrations.RenameField(
            model_name='productinstorepoint',
            old_name='datetime_finished',
            new_name='datetime_ended',
        ),
        migrations.RemoveField(
            model_name='productinstoreinflashsale',
            name='stock_limit',
        ),
        migrations.AddField(
            model_name='product',
            name='is_support_cod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_support_instant_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productinstoreinflashsale',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productinstoreinflashsale',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='productinstore',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productinstore',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productinstorecart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productinstorediscount',
            name='discount_precentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productinstoreinflashsale',
            name='discount_precentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productinstoreinflashsale',
            name='quantity_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productinstorepoint',
            name='point_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RenameModel(
            old_name='Cart',
            new_name='UserCart',
        ),
        migrations.CreateModel(
            name='ProductInUserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_checked', models.BooleanField(default=True)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.usercart')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductInCart',
        ),
    ]
