# Generated by Django 6.0.1 on 2026-02-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_datetime_finished_flashsale_datetime_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
