# Generated by Django 6.0.1 on 2026-01-24 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('voucher', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='user_voucher_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.uservoucherorder'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentmethod'),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod'),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertopupwalletbalancepayment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod'),
        ),
        migrations.AddField(
            model_name='usertopupwalletbalancepayment',
            name='topup_wallet_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.usertopupwalletbalance'),
        ),
    ]
