# Generated by Django 6.0.1 on 2026-02-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='transaction_redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='transaction_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usertopupwalletbalancepayment',
            name='transaction_redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usertopupwalletbalancepayment',
            name='transaction_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
