# Generated by Django 6.0.1 on 2026-01-24 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetflixDiscountPointReedem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('point_required', models.IntegerField()),
                ('min_membership_level', models.IntegerField(default=1)),
                ('netflix_discount_id', models.CharField(max_length=100)),
                ('min_movie_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_precentage', models.IntegerField(default=0)),
                ('max_nominal_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('datetime_started', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherOrderPointReedem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_required', models.IntegerField()),
                ('min_membership_level', models.IntegerField(default=1)),
                ('datetime_started', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNetflixDiscountPointReedem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_reedem', models.DateTimeField(blank=True, null=True)),
                ('netflix_discount_reedem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point.netflixdiscountpointreedem')),
            ],
        ),
    ]
