# Generated by Django 6.0.1 on 2026-01-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixdiscountpointreedem',
            name='discount_precentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='netflixdiscountpointreedem',
            name='min_membership_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='netflixdiscountpointreedem',
            name='point_required',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='voucherorderpointreedem',
            name='min_membership_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='voucherorderpointreedem',
            name='point_required',
            field=models.PositiveIntegerField(),
        ),
    ]
