# Generated by Django 6.0.1 on 2026-02-12 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_usermembership_level_up_point'),
        ('point', '0003_alter_netflixdiscountpointreedem_discount_precentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netflixdiscountpointreedem',
            name='min_membership_level',
        ),
        migrations.RemoveField(
            model_name='voucherorderpointreedem',
            name='min_membership_level',
        ),
        migrations.AddField(
            model_name='netflixdiscountpointreedem',
            name='min_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
        ),
        migrations.AddField(
            model_name='voucherorderpointreedem',
            name='min_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
        ),
    ]
