# Generated by Django 6.0.1 on 2026-02-11 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='pin_number',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'PIN must be exactly 6 digits.')]),
        ),
    ]
