# Generated by Django 6.0.1 on 2026-01-26 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.village'),
        ),
    ]
