# Generated by Django 6.0.1 on 2026-01-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationrule',
            name='point_earned_by_invitee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitationrule',
            name='point_earned_by_inviter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_product_quota',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
