# Generated by Django 6.0.1 on 2026-02-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_invitationrule_point_earned_by_invitee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='dd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='dm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='is_otp_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='nd',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='nm',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
