# Generated by Django 6.0.1 on 2026-01-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='product_in_flashsale',
            new_name='product_in_store_in_flashsale',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='product_in_product_discount',
            new_name='product_in_store_in_product_in_store_discount',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='product_point',
            new_name='product_in_store_point',
        ),
        migrations.AddField(
            model_name='order',
            name='datetime_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='datetime_shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('shipped', 'Shipped'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='rate',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='productinorderreview',
            name='rate',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
